main/urls.py
from .views import home,menu,Reservationcreateview,meal_plan,scrap,blog_detail,remove_from_cart,clear_cart
from django.urls import path
from . import views

urlpatterns=[
    path('',home,name='main'),
    path('menu/',menu,name="menu"),
    path('reservation/',Reservationcreateview.as_view(),name="reservation"),    
  path('menu1/', views.menu_view, name='menu1'),
     path('meal-plan/', meal_plan, name='meal_plan'),
     path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),
    path('place_order/', views.place_order, name='place_order'),
    path('payment/<int:order_id>/', views.payment, name='payment'),
    path('user_orders/', views.user_orders, name='user_orders'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
     path('blog/', scrap, name='blog'),
     path('blogdetail/<path:link>/', blog_detail, name='blog_detail'),
      path('remove-from-cart/<str:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('clear-cart/', clear_cart, name='clear_cart'),
    
]

mysite/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from main import urls as main_urls
from users import urls as user_urls
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
     path('',include(main_urls)),
     path('',include(user_urls)),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import user_directory_path

class MenuSection(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class MenuItem(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    section = models.ForeignKey(MenuSection, related_name='items', on_delete=models.CASCADE)
    Photo=models.ImageField(upload_to=user_directory_path,null=True)
    def __str__(self):
        return self.name
    
class Table(models.Model):
    number = models.PositiveIntegerField(unique=True)
    is_reserved=models.BooleanField(default=False)
    capacity=models.IntegerField(default=6)

    def __str__(self):
        return f"Table {self.number}"    
class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reservations')
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
   
    table = models.OneToOneField(Table, on_delete=models.CASCADE)
    
    

    def __str__(self):
        return f"Reservation by {self.name} for table {self.table.number}"    

class Order(models.Model):
    table_number = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def get_total_price(self):
        total = sum(item.quantity * item.menu_item.price for item in self.items.all())
        return total

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    def __str__(self):
        return f"{self.quantity} x {self.menu_item.name}"

main/forms.py
from django import forms

class DishForm(forms.Form):
    dish_name = forms.CharField(
        label='Dish Name',
        max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': 'Enter the name of the dish',
            'class': 'form-control'
        })
    )

from django import forms
from .models import Order

main/views.py
from django.contrib import messages
from django.shortcuts import render,redirect
from .models import MenuSection,Table
from django.views import View
from .models import Reservation
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from bs4 import BeautifulSoup
import requests
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def home(request):
    return render(request,"views/home.html")

def menu(request):
    sections = MenuSection.objects.prefetch_related('items').all()
    return render(request,"views/menu.html",{'sections': sections})


class Reservationcreateview(View):
    def get(self, request):
        tables = Table.objects.filter(is_reserved=False)
        return render(request, 'views/reservation.html', {'tables': tables})

    def post(self, request):
        if not request.user.is_authenticated:
            # If not logged in, show an error message and reload the form
            messages.error(request, 'You must be logged in to make a reservation.')
            tables = Table.objects.filter(is_reserved=False)
            return render(request, 'views/reservation.html', {'tables': tables})
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        number_of_people = request.POST.get('number_of_people')
        table_id = request.POST.get('table')
        date = request.POST.get('date')
        table = Table.objects.get(id=table_id)
        if Reservation.objects.filter(table=table).exists():
            messages.error(request, 'This table is already reserved for the selected time.')
            tables = Table.objects.filter(is_reserved=False)
            return render(request, 'views/reservation.html', {'tables': tables})

        # Create the reservation object
        Reservation.objects.create(
            user=request.user,
            name=name,
            phone=phone,
            email=email,
           
            table=table,
            
        )
        table.is_reserved=True
        table.save()

        # Optionally, you can add some logic to handle success or failure
        # For example, redirect to a success page or show a message
        return redirect('main')
    
from django.shortcuts import render
from .forms import DishForm
from .services import get_recipe_by_dish_name

# recipe/views.py
from django.shortcuts import render

# views.py
import requests
from django.shortcuts import render
from django.http import JsonResponse
import requests
from django.shortcuts import render
from django.conf import settings

import requests
from django.shortcuts import render
from django.conf import settings

def meal_plan(request):
    if request.method == 'POST':
        target_calories = request.POST.get('target_calories')
        diet = request.POST.get('diet')
        
        url = f"https://api.spoonacular.com/mealplanner/generate?apiKey=2aa152d144034dcdac8d3d32a71a912d&timeFrame=day&targetCalories={target_calories}&diet={diet}"
        
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            meals = data.get('meals', [])
            nutrients = data.get('nutrients', {})
        else:
            meals = []
            nutrients = {}
        
        context = {
            'meals': meals,
            'nutrients': nutrients,
            'target_calories': target_calories,
            'diet': diet
        }
    else:
        context = {
            'meals': [],
            'nutrients': {},
            'target_calories': '',
            'diet': ''
        }
    return render(request, 'views/reciepe.html', context)
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from .models import MenuItem, Order, OrderItem

def menu_view(request):
    
    sections = MenuSection.objects.prefetch_related('items').all()
    return render(request, 'views/menu1.html', {'sections': sections})

def add_to_cart(request):
    if request.method == 'POST':
        item_id = request.POST.get('item_id')
        quantity = int(request.POST.get('quantity', 1))
        menu_item = get_object_or_404(MenuItem, id=item_id)
        
        cart = request.session.get('cart', {})
        if item_id in cart:
            cart[item_id]['quantity'] += quantity
        else:
            cart[item_id] = {'name': menu_item.name, 'price': str(menu_item.price), 'quantity': quantity}
        
        request.session['cart'] = cart
        return JsonResponse({'status': 'success', 'cart': cart})

def view_cart(request):
    cart = request.session.get('cart', {})
    total_price = 0
    
    # Calculate total price
    for item_id, item in cart.items():
        total_price += float(item['price']) * item['quantity']
    
    return render(request, 'views/cart.html', {'cart': cart, 'total_price': total_price})
def remove_from_cart(request, item_id):
    cart = request.session.get('cart', {})
    if item_id in cart:
        del cart[item_id]
        request.session['cart'] = cart  # Update the session cart
    return redirect('view_cart')    
def clear_cart(request):
    request.session['cart'] = {}  # Clear the session cart
    return redirect('view_cart')
def place_order(request):
    if request.method == 'POST':
        table_number = request.POST.get('table_number')
        cart = request.session.get('cart', {})

        order = Order.objects.create(table_number=table_number,user=request.user)
        for item_id, item_data in cart.items():
            menu_item = get_object_or_404(MenuItem, id=item_id)
            OrderItem.objects.create(order=order, menu_item=menu_item, quantity=item_data['quantity'])
        
        request.session['cart'] = {}  # Clear the cart
        return redirect('payment', order_id=order.id)
    
    return redirect('menu')

def payment(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'views/payment.html', {'order': order})
from django.shortcuts import render
import requests
from bs4 import BeautifulSoup

def scrap(request):
    url = "https://www.health.com/nutrition"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    response = requests.get(url, headers=headers)
    print(response)
    blog_items = []
    
    # Parse the response content
    soup = BeautifulSoup(response.content, "html.parser")
    
    # Find the div with the specific id
    dic1 = soup.find('div', id="tax-sc__recirc-list_1-0")
    
    if dic1:
        # Find all anchor tags with the specific class within the div
        as1 = dic1.find_all('a', class_="comp mntl-card-list-items mntl-document-card mntl-card card card--no-image")
        
        for a in as1:
            blog_d = {}
            # Find the img tag with the specific class within the anchor tag
            imgsrc = a.find('img', class_="lazyload card__img universal-image__image")
            if imgsrc:
                blog_d['imgsrc'] = imgsrc['data-src']
                print(imgsrc['data-src'])

            headline = a.find('span', class_="card__title-text")
            if headline:
                print(headline.text)
                blog_d['headline'] = headline.text
            
           
            link = a['href']
            blog_d['link'] = link
            blog_items.append(blog_d)
    else:
        print("No div found with the specified id.")
    
    return render(request, 'views/blog.html', {'blog_items': blog_items})

from django.shortcuts import render
import requests
from bs4 import BeautifulSoup

# Existing scrap view...

def blog_detail(request, link):
    url = link
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    response = requests.get(url, headers=headers)
    print(link)
    soup = BeautifulSoup(response.content, "html.parser")

    
    item = soup.find('div', id="mntl-sc-page_1-0")  # Update the class as per actual HTML


    print("hello")
    blog_content={}
    if item:
        paragraph = item.find_all('p',class_="comp mntl-sc-block mntl-sc-block-html") 
        list=[]
        for p in paragraph:
            list.append(p.text)

         # Adjust to get the relevant paragraph
        imgsrc=item.find('img',class_="primary-image__image mntl-primary-image--blurry loaded")
        print(imgsrc)
        if imgsrc:
            blog_content['imgsrc']=imgsrc['data-src']
            print(imgsrc['data-src'])


   
    blog_content['p']=list
    
    
     
    
    return render(request, 'views/blog_content.html', {'blog_content': blog_content})



@login_required
def user_orders(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, 'views/user_orders.html', {'orders': orders})

@login_required
def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'views/order_detail.html', {'order': order})

main/templates/views/blog.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block 'body' %}

  <div class="container">
  <div class="d-flex flex-wrap">

  {% for blog in blog_items %}


  <div class="card mb-3 blog-item rounded-6">
  <div class="blog-img rounded-6">
   <img src="{{ blog.imgsrc }}" class="card-img-top rounded-9" alt="...">
  </div>
  <div class="card-body">
   <a href="{% url 'blog_detail' link=blog.link %}">
    <h2 class="card-title">{{ blog.headline }}</h2>
    </a>
  </div>
  </div>
{% endfor %}

  </div>
  </div>


  
{% endblock %}

main/templates/views/blog_content.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block 'body' %}
<body>
<div class="card mb-3 blog-cont d-flex justify-content-center align-items-center">
  <h1>Scraped Content</h1>
  <div class="blog-img">
  <img src="{{ blog_content.imgsrc}}" class="blog-img1" alt="Scraped Image">
  </div>
 
  
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
     {% for paragraph in blog_content.p %}
     <p class="p">{{ paragraph }}</p>
        
    {% endfor %}
    
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
  </div>
</div>
  
    
        
    
   
</body>

{% endblock %}

main/templates/views/cart.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block 'body' %}


<div class="cart-div">
<div class="cart-div1" style="">
    <h1 class="mb-4 blur-background" style="margin-left:500px;">Your Cart</h1>
    </div>
    <div class="table-responsive cart-div2">
       <table class="table table-bordered align-middle table-striped" style="border: 3px solid black;">
    <thead style="background-color: #f8d7da; border: 3px solid black;">
        <tr class="table-info">
            <th scope="col" style="border: 3px solid black;">Item Name</th>
            <th scope="col" style="border: 3px solid black;">Price</th>
            <th scope="col" style="border: 3px solid black;">Quantity</th>
            <th scope="col" style="border: 3px solid black;">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% if cart %}
            {% for item_id, item in cart.items %}
                <tr>
                    <td style="border: 3px solid black;">{{ item.name }}</td>
                    <td style="border: 3px solid black;">${{ item.price }}</td>
                    <td style="border: 3px solid black;">{{ item.quantity }}</td>
                    <td style="border: 3px solid black;">
                        <form action="{% url 'remove_from_cart' item_id %}" method="POST" class="d-inline-block">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="4" class="text-center" style="border: 3px solid black;">Your cart is empty.</td>
            </tr>
        {% endif %}
    </tbody>
</table>

    </div>

    {% if cart %}
        <div class="d-flex justify-content-between align-items-center mt-4 cart-div3">
            <h4 class="mb-0">Total: ${{ total_price }}</h4>

            <div class="d-flex gap-2">
                <form action="{% url 'clear_cart' %}" method="POST" class="d-inline-block">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">Clear Cart</button>
                </form>

                <form action="{% url 'place_order' %}" method="POST" class="d-inline-block">
                   <label> enter table number</label>
<input type="number" name="table_number" required>
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">Proceed to Payment</button>
                </form>
            </div>
        </div>
    {% endif %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</div>
{% endblock %}

main/templates/views/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Order</title>
</head>
<body>
    <h1>Create Your Order</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add to Order</button>
    </form>
</body>
</html>

main/templates/views/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block 'body' %}

  <!-- Registration 8 - Bootstrap Brain Component -->
  <div class="firstdiv"> 
  <div id="carouselExampleAutoplaying" class="carousel slide h-100" data-bs-ride="carousel">
 
  <div class="carousel-inner">
    
    <div class="carousel-item position-relative item1 active ">
    <div class="overlay"></div>
   <div class="carousel-caption d-flex-column justify-content-center align-items-center text-center">
        <div>
        <h1 class="text-uppercase tangerine-bold" style="font-size:70px;">Welcome to </h1>
        </div>
        <div>
        <h1 class="text-uppercase rubik-dirt-regular" style="font-size:100px;">MealMate</h1>
        </div>
        <div>
        <button class="btn btn-danger" style="width: 150px; font-size: 30px;height: 80px;"><a href="{% url 'menu1' %}">Menu</a></button> 
        </div>
    </div>
   </div>
   <div class="carousel-item position-relative item2 ">
    <div class="overlay"></div>
   <div class="carousel-caption d-flex-column justify-content-center align-items-center text-center" >
        <div>
        <h1 class="text-uppercase tangerine-bold" style="font-size:70px; ">Make</h1>
        </div>
        <div>
        <h1 class="text-uppercase tangerine-bold" style="font-size:70px;">Reservation</h1>
        </div>
        <div>
         <button  class="btn btn-danger" style="width: 300px; font-size: 30px;height: 80px;"><a href="{% url 'reservation' %}">Reservation</a></button> 
        </div>
    </div>
   </div>
     <div class="carousel-item position-relative item3 ">
    <div class="overlay"></div>
   <div class="carousel-caption d-flex-column justify-content-center align-items-center text-center">
        <div>
        <h1 class="text-uppercase tangerine-bold" style="font-size:70px;"> our new Feature </h1>
        </div>
        
        <div>
        <button href="{% url 'meal_plan' %}"class="btn btn-danger" style="width: 300px; font-size: 30px;height: 80px;"><a href="{% url 'meal_plan' %}">Generate Meal-Plan</a></button> 
        </div>
    </div>
   </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
  </div>



<div class="second d-flex">
    <div class="first-div d-flex fdiv" style="width: 60%;">
        <div class="restaurant-info p-3">
            
            
            <span class="tit2 t-center">
Indian Restaurant
</span>
<h3 class="tit3 t-center m-b-35 m-t-5">
Welcome
</h3>
<p class="t-center m-b-22 size3 m-l-r-auto" style="color: black; font-size:18px;">
Indulge in the authentic flavors of India. From rich curries to flavorful spices, every dish is crafted with tradition and love, bringing a true taste of home to your table.
</p>
        </div>
    </div>
    <div class="second-div m" style="width: 40%;">
        <div class="image-container">
            <img src="{% static 'images/home-welcome-icon1.jpg' %}" alt="Image" class="img-fluid rounded ">
            
            
        </div>
    </div>
</div>

<div class="second d-flex">
    
    <div class="second-div m" style="width: 40%;">
        <div class="image-container" style="margin-left:100px;">
            <img src="{% static 'images/home-meal-plan-icon.jpg' %}" alt="Image" class="img-fluid rounded ">
            
            
        </div>
    </div>
    <div class="first-div d-flex fdiv" style="width: 60%;">
        <div class="restaurant-info p-3">
            <span class="tit2 t-center" style="margin-left:10px;">
             Tailored Meals 
            </span>
<p class="t-center m-b-22 size3 m-l-r-auto" style="color: black; font-size:18px;">
Unlock a personalized meal plan crafted just for you. Based on your calorie needs, we offer balanced meals that blend nutrition with delicious flavors, helping you meet your health goals without compromising on taste.
</p>


              <a href="{% url 'meal_plan' %}" class="btn btn-danger tit3 t-center m-b-35 m-t-5" style="width: 300px; font-size: 30px;margin-left:125px;height: 90px;">Generate Meal-Plan</a> 
             
 

        </div>
    </div>
</div>

<div class="second d-flex">
    <div class="first-div d-flex fdiv" style="width: 60%;">
        <div class="restaurant-info p-3">
            
             <span class="tit2 t-center" style="margin-left:70px;">
              View Our Menu
            </span>
<p class="t-center m-b-22 size3 m-l-r-auto" style="color: black; font-size:18px;">
Discover our carefully curated menu, featuring a variety of dishes that celebrate India's rich culinary heritage. From flavorful curries to aromatic rice and fresh breads, we have something to delight every palate.
</p>


              <a href="{% url 'menu1' %}" class="btn btn-danger tit3 t-center m-b-35 m-t-5" style="width: 300px; font-size: 30px;margin-left:170px;height: 70px;">Menu</a> 

 

        </div>
    </div>
    <div class="second-div m" style="width: 40%;">
        <div class="image-container">
            <img src="{% static 'images/home-menu-icon.jpg' %}" alt="Image" class="img-fluid rounded ">
            
            
        </div>
    </div>
</div>


<div class="second d-flex">
   
    <div class="second-div m" style="width: 40%;">
        <div class="image-container"  style="margin-left:100px;">
            <img src="{% static 'images/home-reservation-icon.jpg' %}" alt="Image" class="img-fluid rounded ">
            
            
        </div>
    </div>

     <div class="first-div d-flex fdiv" style="width: 60%;">
        <div class="restaurant-info p-3">
            
             <span class="tit2 t-center" style="margin-left:70px;">
              Make Reservation
            </span>
<p class="t-center m-b-22 size3 m-l-r-auto" style="color: black; font-size:18px;">
Reserve your table today and enjoy an unforgettable dining experience. Immerse yourself in the warm, inviting ambiance, where every detail is crafted to enhance your journey through the rich flavors of India. Whether it’s an intimate meal or a celebration, our restaurant provides the perfect setting for any occasion.
</p>


              <a href="{% url 'reservation' %}" class="btn btn-danger tit3 t-center m-b-35 m-t-5" style="width: 300px; font-size: 30px;margin-left:200px;height: 70px;">Reservation</a> 

 

        </div>
    </div>
</div>

{% endblock %}

main/templates/views/menu.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block 'body' %}


<div class="d-flex flex-column">


<div class="d-flex align-items-center justify-content-center menu">
    <div class="overlay2 d-flex align-items-center justify-content-center">
          <h1 class=" lobster-regular">Menu</h1>
    </div>
</div>




 {% for section in sections %}
 <div class="menupg overlay2 d-flex">
 {% if forloop.counter|divisibleby:2 %}
     <div class="second-div d-flex flex-column align-items-center justify-content-center " style="width: 60%;">
        <div class="image-container">
            <img src="{% static 'images/Biryani1.jpg' %}" alt="Image" class="img-fluid rounded "> 
        </div>
     </div>   
    <div class="d-flex flex-column align-items-centre justify-content-center " style="width:40%">
        <h1>{{ section.name }}</h1>
       
        <div>
            <ol> 
             {% for item in section.items.all %}
                            <li class="">{{ item.name }} - ${{ item.price }}</li>
                        {% endfor %}
            </ol>
        </div>
    </div>

{% else %}
 
    <div class="d-flex flex-column align-items-centre justify-content-center " style="width:40%;margin-left:110px;">
        <h1>{{ section.name }}</h1>
       
        <div>
            <ol> 
             {% for item in section.items.all %}
                            <li class="">{{ item.name }} - ${{ item.price }}</li>
                        {% endfor %}
            </ol>
        </div>
    </div>
     <div class="second-div d-flex flex-column align-items-center justify-content-center " style="width: 50%;">
        <div class="image-container">
            <img src="{% static 'images/Biryani1.jpg' %}" alt="Image" class="img-fluid rounded "> 
        </div>
     </div>  


{% endif %}
</div>
{% endfor %}


</div>


{% endblock %}

main/templates/views/menu1.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block 'body' %}

   
 <div class="menupage" style="background-color:">
 <div class="d-flex align-items-center justify-content-center menu">
    <div class="overlay2 d-flex align-items-center justify-content-center">
          <h1 class="bungee-shade-regular">Menu</h1>
    </div>
</div>

    

   {% for section in sections %}
   
   <div class="shadow-text">
   
   <h1 class="blur-background shadow-text" style="color:red;">{{section.name}}</h1>
     
   </div>
    
    <div class="overlay2 d-flex menu-category align-items-center justify-content-center flex-wrap menucontainer" style="background-image: url({% static 'images/meal-plan.jpg' %});"
>


    {% for item in section.items.all %}
     
     <div class="col-md-3 mb-4 flex-wrap1 menuitem1 ">
     <div class="card h-100 ">
      
      <div  class="menu-item-image rounded-5" style="heigth: 70%;">
       <img src="{{item.Photo.url}}" alt="Menu Item Image" class="card-img-top img-fluid ">

      </div>
      <div class="card-body">
      <div style="heigth: 40%;">
      <h5 class="card-title">{{ item.name }}</h5>
      <p class="card-text"> ${{ item.price }}</p>
      <input type="number" id="quantity-{{ item.id }}" name="quantity" min="1" value="1">
                <button class="btn btn-primary" onclick="addToCart({{ item.id }})">Add to Cart</button>
      </div>

       
      
    </div>
   
  </div>
   </div>


    {% endfor %}
       
        </div>
       



    {% endfor %}                    
    <a href="{% url 'view_cart' %}">View Cart</a>
  
   
</div>
    <script>
        function addToCart(itemId) {
            const quantity = document.getElementById(`quantity-${itemId}`).value;
            $.post("{% url 'add_to_cart' %}", {
                item_id: itemId,
                quantity: quantity,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }).done(function(data) {
                alert("Item added to cart");
            });
        }
    </script>
{% endblock %}

main/templates/views/reservation.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block 'body' %}
<div class="container dining d-flex justify-content-center align-items-center">

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} my-2">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

<div class=" container reservation d-flex justify-content-center align-items-center" >
        <div>
        <h1 class="blur-background">Create Reservation</h1>
    
        <form  method="post" style="width:70%; margin-left:90px;" >
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name"></label>
                <input type="text" class="form-control" id="id_name" name="name" placeholder="Your Name">
            </div>
            <div class="form-group">
                <label for="id_phone"></label>
                <input type="text" class="form-control" id="id_phone" name="phone" placeholder="Your Phone Number">
            </div>
            <div class="form-group">
                <label for="id_email"></label>
                <input type="email" class="form-control" id="id_email" name="email" placeholder="Your Email">
            </div>
          
             <div class="form-group">
                <label for="id_table"></label>
                <select class="form-control" id="id_table" name="table">
                    {% for table in tables %}
                        <option value="{{ table.id }}">Table {{ table.number }} Capacity {{table.capacity}}</option>
                    {% endfor %}
                </select>
            </div>

            
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

</div>



</div>


</div>


    {% endblock %}